#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#define VENDOR_NAME "RIVIR"
#define PRODUCT_NAME "MCUboot M4_CAN"
#define VOLUME_LABEL "RIVIRBOOT"
#define INDEX_URL "http://rivir.space"
#define BOARD_ID "SAME51J20A-RIVIR-M4-1"

#define USB_VID 0x239A
#define USB_PID 0x00CD

#define LED_PIN PIN_PA23

#define BOARD_NEOPIXEL_POWERPIN PIN_PB03
#define BOARD_NEOPIXEL_PIN PIN_PB02
#define BOARD_NEOPIXEL_COUNT 1

#define BOOT_USART_MODULE                 SERCOM0
#define BOOT_USART_MASK                   APBAMASK
#define BOOT_USART_BUS_CLOCK_INDEX        MCLK_APBAMASK_SERCOM0
#define BOOT_USART_PAD_SETTINGS           UART_RX_PAD3_TX_PAD0
#define BOOT_USART_PAD3                   PINMUX_PA07D_SERCOM0_PAD3
#define BOOT_USART_PAD2                   PINMUX_UNUSED
#define BOOT_USART_PAD1                   PINMUX_UNUSED
#define BOOT_USART_PAD0                   PINMUX_PA04D_SERCOM0_PAD0
#define BOOT_GCLK_ID_CORE                 SERCOM0_GCLK_ID_CORE
#define BOOT_GCLK_ID_SLOW                 SERCOM0_GCLK_ID_SLOW

#endif
